spring:
    #项目名称
    application:
        name: millionBlog
    # 环境 dev:测试环境|prod:生产环境
    profiles:
        active: dev #激活的配置文件

    # springboot静态资源配置
    resources:
        static-locations: classpath:/templates
    mvc:
        static-path-pattern: /**

    #jdbc
    datasource:
        druid:
            initial-Size: 5
            max-Active: 20
            max-Wait: 60000
            time-Between-Eviction-Runs-Millis: 60000
            min-Evictable-Idle-Time-Millis: 300000
            validation-Query: SELECT 1 FROM DUAL
            test-While-Idle: true
            test-On-Borrow: false
            test-On-Return: false
            filters: stat,wall,logback

    #redis
    redis:
        #redis 支持16个数据库（相当于不同用户）可以使不同的应用程序数据彼此分开同时又存储在相同的实例上
        database: 0
        # 服务器地址 变更为自己的
        host: localhost
        # 服务器连接端口
        port: 6379
        # 服务器连接密码（默认为空）如果有变更为自己的
        #spring.redis.password=***
        #redis 缓存数据过期时间单位秒
        expiration: 3000
        #控制一个 pool 可分配多少个jedis实例
        pool.max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        pool.max-wait: -1
        # 连接池中的最大空闲连接
        pool.max-idle: 8
        # 连接池中的最小空闲连接
        pool.min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 30000

    #thymeleaf
    thymeleaf:
        #缓存
        cache: false
        #模版
        mode: HTML5
        #是否启用
        enabled: true
        #前缀
        prefix: classpath:/templates/
        #后缀
        suffix: .html
        servlet:
            #文本类型
            content-type: text/html
    #切面
    aop:
        auto: true

logging:
    config: classpath:logback-spring.xml # 日志配置文件

# xml配置路径
mybatis:
    mapper-locations: classpath:sql/*Mapper.xml
    typeAliasesPackage: com.kcy.system.model
#pageHelper
pageHelper:
    offsetAsPageNum=true:
    #该参数默认为false
    #设置为true时，使用RowBounds分页会进行count查询
    rowBoundsWithCount: true
    reasonable: true
    #方言
    dialect: mysql

#关闭beetlsql
beetlsql:
    enabled: false
#开启beetl
beetl:
    enabled: true