spring:
  #mq
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    username: million
    password: million526113
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.52.129:3306/million?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#接口文档   //生产模式需要关闭swagger
swagger:
  enabled: false

#文件上传地址
uploadImgPrefix: "/million/opt"
uploadImgPre: "http://39.106.52.129"

#根路径，端口
server:
  context-path: /
  port: 80
